### ISSUE TITLE
Form Input Directive Lesson

### ISSUE THREAD

**Issue by jackygrahamez** [jackrabbitsgroup/learn-mean-seed#2]
Hey Luke, it is really cool you have these lessons here, as I am new to Angular. I am getting confused by the lessons. I looked at this first one last night and I ignored my issues and then had trouble with the next one today. So I'm going back to the start to try to address them. The directions say:

```
1. Add " placeholder='my text' " to the jrg-forminput div element (right before the ></div>) to make a 'placeholder' and 'label' show up for the input.
```

I open this file

```
/src/modules/pages/angular/directive/use/forminput/angular-forminput-basic.html
```

and I see this

```
<div jrg-forminput ng-model='text' opts='' placeholder='my text'></div>
```

So it appears the work is already done for this?  Is there something else I'm supposed to do in this lesson?

I'll post my other lesson questions separate.

**Comment by lukemadera** [comment]
Bug! Good catch; it was already complete. Fixed.
